// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    var displayPage, element, onMenuElementClicked, path, url;
    onMenuElementClicked = (function(_this) {
      return function(event) {
        var page;
        page = event.target.id.substring(5);
        return displayPage(page);
      };
    })(this);
    displayPage = (function(_this) {
      return function(page) {
        _this.lastSelectedMenu.removeClass('selected');
        _this.lastSelectedMenu = $("#menu-" + page);
        _this.lastSelectedMenu.addClass('selected');
        _this.lastSelected.fadeOut(300, function() {
          return $("#" + page).fadeIn(300);
        });
        return _this.lastSelected = $("#" + page);
      };
    })(this);
    if ($(window).width() > 760) {
      $('#install').hide();
      $('#documentation').hide();
      $('#contact').hide();
      $('#developers').hide();
      $('#demo').hide();
      $('#faq').hide();
    }
    $('#download-text').click(function(event) {
      return displayPage('install');
    });
    $('#menu-home').click(onMenuElementClicked);
    $('#menu-install').click(onMenuElementClicked);
    $('#menu-faq').click(onMenuElementClicked);
    $('#menu-documentation').click(onMenuElementClicked);
    $('#menu-contact').click(onMenuElementClicked);
    $('#menu-developers').click(onMenuElementClicked);
    $('#menu-demo').click(onMenuElementClicked);
    url = document.location.href;
    if (url && url.indexOf("#") > 0) {
      path = url.split("#")[1];
      element = "#" + path;
      $('#home').hide();
      $(element).show();
      this.lastSelected = $(element);
      this.lastSelectedMenu = $('#menu-' + path);
    } else {
      this.lastSelected = $('#home');
      this.lastSelectedMenu = $('#menu-home');
    }
    return this.lastSelectedMenu.addClass('selected');
  });

}).call(this);
