// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    var displayInstall, displayPage, element, lastSelected, lastSelectedMenu, onMenuElementClicked, path, url,
      _this = this;
    $('#install').hide();
    $('#documentation').hide();
    $('#contact').hide();
    $('#developers').hide();
    $('#faq').hide();
    lastSelected = $('#home');
    lastSelectedMenu = $('#menu-home');
    lastSelectedMenu.addClass('selected');
    displayInstall = function(event) {
      return displayPage('install');
    };
    $('#menu-install').click(displayInstall);
    $('#download-text').click(displayInstall);
    onMenuElementClicked = function(event) {
      var page;
      page = event.target.id.substring(5);
      return displayPage(page);
    };
    displayPage = function(page) {
      lastSelectedMenu.removeClass('selected');
      lastSelectedMenu = $("#menu-" + page);
      lastSelectedMenu.addClass('selected');
      lastSelected.fadeOut(300, function() {
        return $("#" + page).fadeIn(300);
      });
      return lastSelected = $("#" + page);
    };
    $('#menu-home').click(onMenuElementClicked);
    $('#menu-faq').click(onMenuElementClicked);
    $('#menu-documentation').click(onMenuElementClicked);
    $('#menu-contact').click(onMenuElementClicked);
    $('#menu-developers').click(onMenuElementClicked);
    url = document.location.href;
    if (url && url.indexOf("#") > 0) {
      path = url.split("#")[1];
      element = "#" + path;
      $('#home').hide();
      $(element).show();
      lastSelected = $(element);
      lastSelectedMenu.removeClass('selected');
      lastSelectedMenu = $('#menu-' + path);
      return lastSelectedMenu.addClass('selected');
    }
  });

}).call(this);
