#!/bin/sh
#

### BEGIN INIT INFO
# Provides:          nginx
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the nginx web server
# Description:       starts nginx using start-stop-daemon
### END INIT INFO


NEWEBE_PATH=/home/newebe/newebe/
PIDFILE="/home/newebe/newebe/newebe.pid"

# Handle manual control parameters like start, stop, status, restart, etc.

case "$1" in
  start)
    echo "Starting newebe..."
    cd $NEWEBE_PATH
    python newebe_server.py
    ;;

  stop)
    # Stop daemons.
    echo "Shutting down newebe... "
    kill `cat -- $PIDFILE`

    ;;
  restart)
    $0 stop
    $0 start
    ;;

  *)
    echo $"Usage: $0 {start|stop|restart}"
    exit 1
esac

exit 0


