#!/bin/sh
#

DAEMON_DIR="/home/newebe/newebe"
DAEMON="/usr/bin/python $DAEMON_DIR/newebe_server.py"

DAEMON_OPT="" 
DAEMON_USER="newebe" 
DAEMON_NAME="newebe" 
PIDFILE=/var/run/$DAEMON_NAME.pid 

PATH=/usr/sbin:/usr/bin:/sbin:/bin

. /lib/lsb/init-functions

case "$1" in

        start)
                log_daemon_msg "Starting Newebe server..."
                start-stop-daemon --start --pidfile $PIDFILE \
                    --chdir $DAEMON_DIR --name $DAEMON_NAME \
                    -c $DAEMON_USER \
                    --make-pidfile --background --exec $DAEMON
                  case "$?" in
                    0|1) log_end_msg 0 ;;
                    2) log_end_msg 1 ;;
                  esac
                ;;
        
        stop)
                log_daemon_msg "Stopping Newebe server..."
                start-stop-daemon --stop --quiet --oknodo \
                    --pidfile $PIDFILE 
                rm -f $PIDFILE 
                case "$?" in
                  0|1) log_end_msg 0 ;;
                  2) log_end_msg 1 ;;
                esac
                ;;

        restart|force-reload)
                $0 stop
                sleep 1
                $0 start
                ;;
        *)
                echo "Usage: /etc/init.d/$DEAMON_NAME {start|stop|restart}"
                exit 1
                ;;
esac
exit 0
