#!/bin/bash
 
# Replace these three settings to match your newebe directory.
PROJDIR="/home/newebe/newebe"
PIDFILE="/home/newebe/newebe/newebe.pid"
PORT=8000
 
case "$1" in
    # Start run your newebe app in Fast CGI mode on specified port.
    start)
      cd $PROJDIR
      python manage.py runfcgi method=prefork host=127.0.0.1 port=$PORT pidfile=$PIDFILE
     RETVAL=$?
  ;;
    # Stop the fast cgi script.
    stop)
      kill `cat -- $PIDFILE`
      rm -f -- $PIDFILE
      RETVAL=$?
  ;;
    # Stop then start newebe Fast CGI script
    restart)
      kill `cat -- $PIDFILE`
      rm -f -- $PIDFILE
      cd $PROJDIR
      python manage.py runfcgi method=prefork host=127.0.0.1 port=$PORT pidfile=$PIDFILE
      RETVAL=$?
  ;;
    *)
      echo "Usage: projet_django {start|stop|restart}"
      exit 1
  ;;
esac      
exit $RETVAL
