#!/bin/sh
#

### BEGIN INIT INFO
# Provides:          newebe
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the newebe daemon
# Description:       starts newebe daemon
### END INIT INFO



