#! /bin/sh
# postinst script for newebe
# $Id: newebe.postinst,v 1.0 2012/11/26 21:39:04 hmh Exp $

set -e

case "$1" in
    configure)
	# add newebe system user (requires adduser >= 3.34)
	echo "Creating/updating newebe user account..."
	adduser --system --ingroup newebe --home /var/run/newebe \
		--gecos "Newebe system user" --shell /bin/false \
		--quiet --disabled-password newebe

        echo "
main:
    path: "/var/run/newebe/"
security:
    certificate: "/var/run/newebe/certs/server.crt"
    private_key: "/var/run/newebe/certs/server.key"
        " > /etc/newebe/config.yaml

        mkdir /etc/newebe
        cd /var/run/newebe
        mkdir certs
        cd certs
        openssl genrsa -out ./server.key 1024
        openssl req -new -x509 -days 3650 -key ./server.key -out ./server.crt
        cd ..
        chown -R newebe:newbe certs

        echo "
[program:newebe]
autorestart=false
command=newebe_server.py --configfile=/etc/newebe/config.yaml
redirect_stderr=true
user=newebe
" > /etc/supervisor/conf.d/newebe.config
        sudo supervisorctl update
        
        
        ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

exit 0
