#! /bin/sh
# postinst script for newebe
# $Id: newebe.postinst,v 1.0 2012/11/26 21:39:04 hmh Exp $

set -e

case "$1" in
    configure)
	# add newebe system user (requires adduser >= 3.34)
	echo "Creating/updating newebe user account..."
        
        if ! id newebe > /dev/null 2>&1
        then
            adduser --system --ingroup newebe --home /usr/local/newebe \
                    --gecos "Newebe system user" --shell /bin/false \
                    --quiet --disabled-password  --group newebe
        fi

        if [ ! -d "/usr/local/newebe" ]; then
            mkdir /usr/local/newebe
        fi
        chown -R newebe:newebe /usr/local/newebe
        
        if [ ! -d "/usr/local/var/log/newebe" ]; then
            mkdir /usr/local/var/log/newebe
        fi
        chown -R newebe:newebe /usr/local/var/log/newebe
        
        if [ ! -d "/etc/newebe" ]; then
            mkdir /usr/local/etc/newebe
        fi
        chown -R newebe:newebe /usr/local/etc/newebe
        echo "
main:
    path: "/usr/lcocal/newebe/"
    path: "/usr/local/var/log/newebe/"
security:
    certificate: "/usr/local/etc/newebe/certs/server.crt"
    private_key: "/usr/local/etc/newebe/certs/server.key"
        " > /usr/local/etc/newebe/config.yaml

        cd /usr/local/etc/newebe

        if [ ! -d "certs" ]; then
            mkdir certs 
        fi
        cd certs
        openssl genrsa -out ./server.key 1024
        openssl req -new -x509 -days 3650 -key ./server.key \
                -out ./server.crt -batch
        
        cd ..
        chown -R newebe:newebe /usr/local/etc/newebe/certs

        touch /usr/share/pyshared/newebe/apps/__init__.py
        touch /usr/share/pyshared/newebe/tools/__init__.py
        touch /usr/share/pyshared/newebe/lib/__init__.py

        echo "
[program:newebe]
autorestart=false
command=newebe_server.py --configfile=/etc/newebe/config.yaml
redirect_stderr=true
user=newebe
" > /etc/supervisor/conf.d/newebe.conf
        supervisorctl update
        ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

exit 0
