#! /bin/sh
# postinst script for newebe
# $Id: newebe.postinst,v 1.0 2012/11/26 21:39:04 hmh Exp $

set -e

case "$1" in
    configure)
	# add newebe system user (requires adduser >= 3.34)
	echo "Creating/updating newebe user account..."
        if ! grep -i "^newebe" /etc/group
        then
            groupadd newebe
        fi

        if ! id newebe > /dev/null 2>&1
        then
            adduser --system --ingroup newebe --home /var/lib/newebe \
                    --gecos "Newebe system user" --shell /bin/false \
                    --quiet --disabled-password newebe
        fi

        if [ ! -d "/var/lib/newebe" ]; then
            mkdir /var/lib/newebe
        fi
        chown -R newebe:newebe /var/lib/newebe
        if [ ! -d "/etc/newebe" ]; then
            mkdir /etc/newebe
        fi
        echo "
main:
    path: "/var/lib/newebe/"
security:
    certificate: "/etc/newebe/certs/server.crt"
    private_key: "/etc/newebe/certs/server.key"
        " > /etc/newebe/config.yaml

        cd /etc/newebe

        if [ ! -d "certs" ]; then
            mkdir certs 
        fi
        cd certs
        openssl genrsa -out ./server.key 1024
        openssl req -new -x509 -days 3650 -key ./server.key -out ./server.crt
        cd ..
        chown -R newebe:newebe /etc/newebe/certs

        sudo touch /usr/share/pyshared/newebe/apps/__init__.py
        sudo touch /usr/share/pyshared/newebe/tools/__init__.py
        sudo touch /usr/share/pyshared/newebe/lib/__init__.py

        echo "
[program:newebe]
autorestart=false
command=newebe_server.py --configfile=/etc/newebe/config.yaml
redirect_stderr=true
user=newebe
" > /etc/supervisor/conf.d/newebe.conf
        supervisorctl update
        ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

exit 0
